# Generated by Django 4.1.2 on 2022-10-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="name",
            new_name="theme",
        ),
    ]
