# Generated by Django 4.1.2 on 2022-10-17 19:52

from django.db import migrations
from authentication.services import create_dev_user


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20221017_2251"),
    ]

    operations = [migrations.RunPython(create_dev_user)]
