# Generated by Django 4.1.2 on 2022-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ware", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(max_length=250, null=True),
        ),
    ]
