# Generated by Django 4.1.2 on 2022-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ware", "0002_product_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_link",
            field=models.TextField(max_length=400, null=True),
        ),
    ]
