name: Check code quality

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # - name: Install Pipenv
      #   run: pip install pipenv

      - name: Install Dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
          
      - name: Run black
        run: black --check ./

      - name: Run isort
        run: isort --check-only .     
        
      - name: Run linter
        run:  flake8 ./
