name: Check code quality

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: |
          pipenv install --deploy --ignore-pipfile

      - name: Cleanup
        run: |
          pipenv --rm
      
      - name: Install Black
        run: pip install black
          
      - name: Run black
        run: black --check ./

      - name: Run isort
        run: isort --check-only ./      
        
      - name: Run linter
        run:  flake8 ./
