name: Check code quality

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
  
      - name: Install pipenv
        run: pip install pipenv
  
      - name: Install Dependencies with pipenv
        run: pipenv install --dev
  
      - name: Run Black
        run: pipenv run black .
  
      - name: Run isort
        run: pipenv run isort --check-only .     
        
      - name: Run linter
        run:  flake8 ./
