name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Или другая ветка, на которой вы хотите запускать действие

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Версия Node.js

      - name: Install Dependencies
        working-directory: ./frontend  # Папка фронтенда
        run: npm install

      - name: Build
        working-directory: ./frontend  # Папка фронтенда
        run: npm run build
